# User config
author: "DhammaCharts"
# tagline: "Pineapple Certfied Jekyll Theme"
# description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
keywords: "Dhamma, Chart"
email: "dhammacharts@protonmail.com"
# linkedin: "https://www.linkedin.com/"
# twitter: "https://twitter.com/"
# github: "https://github.com/"# User config
author: "DhammaCharts"
# tagline: "Pineapple Certfied Jekyll Theme"
# description: "In 1493, explorer Christopher Columbus found pineapples on Guadeloupe Island in the Caribbean. Pineapple on pizza soon followed..."
keywords: "Dhamma, Chart"
email: "dhammacharts@protonmail.com"
# linkedin: "https://www.linkedin.com/"
# twitter: "https://twitter.com/"
# github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed